sudo: required
services:

language: node_js
node_js:
  - "5"
before_install:

  # Install chrome & chromium
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update && sudo apt-get install -y google-chrome-stable
  # Install xvfb
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
  # Install chrome & chromium

  - sudo apt-get update && sudo apt-get install -y chromium-bsu
  # Install UI test requirements
  - npm install -g protractor@3.3.0 grunt-cli
#  - npm install -g protractor@4.0.9 grunt-cli
  - webdriver-manager update #--versions.chrome 2.24
  # Update Ruby cucumber dependencies

  # Update Node UI test dependencies

  - npm install
  - npm ls

  # Version reporting

  # Install xvfb
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  # - sleep 3 # give xvfb some time to start
  # Run Delete Script to empty DynamoDB before tests start

  # Reset ECOG Mock service Data

script:


  # Run Cucumber end to end tests
  # - bundle exec cucumber --tags @EndtoEnd
  # Install xvfb
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  # Run UI tests

#  - protractor config.js --cucumberOpts.tags='~@broken' --cucumberOpts.tags=$CUC_TAG$PRIORITY --troubleshoot
  # Run protractor only if the tag is UI or demo
  - protractor config.js
  # Generate html report

after_success:
  #Run P3 cucumber tests

  #Run protractor tests


  # tag docker image with date and deploy to UAT
#  - ./dockerdeploy.sh
  # Trigger Travis script #3, UAT Tests
#  - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json" -H "Travis-API-Version:3" -H "Authorization:token $UAT_TRAVIS_TOKEN" -d "{\"request\":{\"message\":\"Triggered by $TRIGGER_REPO $TRAVIS_COMMIT\", \"branch\":\"master\", \"config\":{\"env\":{\"matrix\":[\"TRIGGER_REPO=$TRIGGER_REPO;CUC_TAG=$CUC_TAG\"]}}}}" https://api.travis-ci.org/repo/CBIIT%2Fnci-uMatch-uattests/requests
after_failure:
    #Run P3 cucumber tests

after_script:
  #Set above, - export DATE=`TZ=America/New_York date "+%m-%d-%y-%H%M"`
  - export DATE_TRIM=`TZ=America/New_York date "+%m-%d-%y"`
  #Send result json to S3 for review
  ######COMMENTING FOR NOW###########################
#  - aws s3 cp ~/build/CBIIT/nci-uMatch-bddtests/results s3://cucumbertest-reports/$TRIGGER_REPO/$DATE-$TRAVIS_BUILD_NUMBER/ --region us-east-1 --recursive
  ###################################################

  #- aws s3 cp ~/build/CBIIT/nci-uMatch-bddtests/results/result.json s3://cucumbertest-reports/$TRIGGER_REPO/$DATE-$TRAVIS_BUILD_NUMBER/ --region us-east-1

  #purge queues
#  - aws sqs purge-queue --queue-url https://sqs.us-east-1.amazonaws.com/127516845550/ion_reporter_queue
#  - aws sqs purge-queue --queue-url https://sqs.us-east-1.amazonaws.com/127516845550/patient_queue
#  - aws sqs purge-queue --queue-url https://sqs.us-east-1.amazonaws.com/127516845550/patient_queue_deadletter
#  - aws sqs purge-queue --queue-url https://sqs.us-east-1.amazonaws.com/127516845550/treatment_arm_queue
######COMMENTING FOR NOW###########################
#  - export DATE=`TZ=America/New_York date "+%m-%d-%y-%H%M"`
#  - export TEST_REPORT='BDD Test Report'
#  - cd ~/build/CBIIT/nci-uMatch-bddtests/ResultsUpload
#  - ./update_google_drive.rb -d ~/build/CBIIT/nci-uMatch-bddtests/results/ -c config.json -t $CUC_TAG -b $TRAVIS_BUILD_NUMBER -f $TEST_REPORT
###################################################
  # - aws s3 cp ~/build/CBIIT/nci-uMatch-bddtests/uMATCH/PedMATCH/results/output.json s3://cucumbertest-reports/$TRIGGER_REPO/$DATE-$TRAVIS_COMMIT/ --region us-east-1
  # - aws s3 cp ~/build/CBIIT/nci-uMatch-bddtests/nci-match-ui-bddtests/results/result.json s3://cucumbertest-reports/$TRIGGER_REPO/$DATE-$TRAVIS_COMMIT/ --region us-east-1
notifications:
